setting:
  # 是否启用模块
  enable: false
# 更新时间 (单位: Tick)
update-time: 10

# 记分板
boards:
  #记分板标题
  title: '玩家信息'
  lines:
    - '&6名 称: &a%player_displayname%'
    - '&6世 界: &b%player_world%'
    - '&6位 置: &3%player_x%,%player_y%,%player_z%'
    - '&6等 级: &e%player_level%'
    - '&6血 量: &c%player_health%'
    - '&6饥 饿: &d%player_food_level%'
    - '&6模 式: &4%player_gamemode%'